# Generated by Django 5.2.3 on 2025-06-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nickname', models.CharField(max_length=100, verbose_name='Foydalanuvchi nomi')),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
            ],
        ),
    ]
