# Generated by Django 5.2.3 on 2025-06-27 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_fish', models.CharField(max_length=256)),
                ('fakultet', models.TextField(max_length=256)),
                ('fakultet_raqami', models.PositiveIntegerField()),
                ('guruh_raqami', models.CharField(max_length=256)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('format', models.CharField(choices=[('Elektron', 'Elektron'), ('Bosma', 'Bosma'), ('Qo`l yozma', 'Qo`l yozma')], default='Elektron', max_length=56)),
                ('publication_type', models.CharField(max_length=256)),
                ('journal_name', models.CharField(max_length=256)),
                ('volume', models.PositiveIntegerField()),
                ('issue', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField()),
                ('pages', models.CharField(max_length=56)),
                ('bet_soni', models.PositiveIntegerField()),
                ('mualliflar_soni', models.PositiveIntegerField()),
                ('piece', models.CharField(blank=True, max_length=256)),
                ('authors', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
